### ISSUE TITLE
Metadata usage may be problematic

### ISSUE THREAD

**Issue by displague** [equinix/cloud-provider-equinix-metal#183] opened 2021-06-22 20:45 UTC
The Equinix Metal metadata service is currently consumed under conditions where the Facility was not specified via configuration.

The metadata is fetched from any node in the cluster. There are some problems with this:
- using metadata to determine the facility of one node in the cluster, does not guarantee that other nodes in the cluster are located in the same facility. The default portal behavior is to provision nodes in metros, which could result in nodes landing in multiple facilities.
- in a heterogenous cloud setup, the ccm could be running on nodes not in EM (while managing EM nodes). the metadata service would not be available.

One example of metadata use is: https://github.com/equinix/cloud-provider-equinix-metal/blob/b686e3fd36bfa8bf2aefd890e2bef168d8b8b620/main.go#L136-L144

**Comment by flokli** [comment] 2021-06-22 21:06
I think some of the tasks the CCM does should be splitted.

 - have a generic Deployment-type controller that talks to the EM API. When new nodes appear in the cluster, it can do some initial investigation on whether this is likely to be a packet node (by comparing the nodes' reported external IP with what's visible in the cluster for example, and add a (soft) annotation so the DaemonSet below gets scheduled)
 - have a DaemonSet running on each possible packet node, reading the local metadata, and adding more annotations/labels:
   - whether it really is a packet node
   - which facility it's running on
   - which metro it's running on
   - its BGP config

The Deployment can pick up annotation changes and update BGP config, as it already does.

**Comment by deitch** [comment] 2021-06-23 09:09
There are a few issues mixed together here. I am going to try and tease them out. Keep in mind that we use facility in two places:

1. load balancers, when creating the EIP, needs to know in which facility (future: metro) to create it
2. the cloud-provider API for `Zones` - this does not use the metadata or the env var, just reading it directly from the node information retrieved via EQXM API, so out of scope.

The issues:

* ccm assumes that all nodes are running in EQXM; in reality, it could be multi-cloud.
* ccm assumes that all nodes are running in one facility; in reality, it could be across multiple facilities in a single metro, or across metros.
* ccm assumes that the (single) facility is the only place that the ccm itself is running, and thus it can use metadata to retrieve that facility

I think we can ignore the first issue. In general, clusters should not be run across regions in a single cloud, let alone across clouds. The second issue can be half-ignored for the same reason: people should not be running a single cluster across ewr1 and dal1, let alone hkg1.

For that matter, even if we wanted to support it, despite its anti-pattern-ness, we couldn't. How would a load balancer work? Would the load balancer EIP come from EQXM? The operator's directly owned IPs? The other cloud provider?

The second part of the second issue - multiple nearby facilities in a single metro - needs to be addressed. The assumption that everything is in one facility simply isn't true any longer

The third issue usually was dealt with by overriding the env var. That works, for the most part, for running it locally (off-cluster), which is why it was created. We may need a little more intelligence here, perhaps using the EQXM API instead of metadata. The question is, what facility would it look for? It could get all of the nodes it knows about, but what if no nodes have yet been deployed on EQXM?

This may need a bit of a rethink as to how facilities are used, and to start to support metros. Here are some thoughts, first cut.

1. facility env var override continues to be supported; when provided, EIP always is requested for the given facility
2. when facility is not provided, instead of metadata on whatever node CCM pod is running, use the EQXM API to get the facility. As mentioned above, this is used _only_ for the facility to request EIPs for services of `type=LoadBalancer`. The problematic question is when to make that query. CCM itself might be deployed before any nodes are available, and which node's facility should it use?
3. Should we request for the facility of the node (when using discovery) or the metro?

**Comment by deitch** [comment] 2021-06-23 09:10
@flokli we are hesitant to complicate this by adding a new process in a container as a `DaemonSet` that has to run on each node. I also am not sure we need it. Every node that gets launched is passed to the CCM via k8s events. We can (and do) execute the EQXM API seeking data about that node, and use it to update the annotations.

What more do we need for it?

**Comment by displague** [comment] 2021-06-24 15:35
I was chatting with @rawkode about the ToR routes needed in some conditions. 

Based on the documentation https://kubernetes.io/docs/concepts/architecture/cloud-controller/#route-controller, it seems we could use the Route controller aspect of the cloud-provider to automatically provide these routes (169.254.255.1, 169.254.255.2).

This would suggest that a daemonset approach for the cloud provider would be needed.

**Comment by deitch** [comment] 2021-06-29 10:59
> use the Route controller aspect of the cloud-provider to automatically provide these routes

My understanding of this is that the `Routes()` is called when the kube-apiserver wants the routes to be set up, and it is done once. It doesn't get executed for each node. In this case, we would want each node to have the routes created. I am not sure how `Routes()` (routes controller) would help with this. We still would need a DaemonSet, which still would need to run on every node (or a one-time on each node, although the routes would need to be persistent).

We still are very hesitant to add another layer of complexity by having a daemonset that needs to be deployed for this to work, as opposed to setting the source route (or, just have the upstream BGP peers accept the packets from the default source IP, which would seem to be more sane, but configurable source IP is a common network software behaviour).

One interesting trick that we _did_ do with the EM CCM for control plane ELB was to leverage kube-proxy to create routes we wanted. If you set up a `Service` with specific `Endpoints`, kube-proxy sets up routes on each node to route to it. We did it specifically to avoid running a DaemonSet.

I don't see quite offhand how that would work here, as we need not just the route but the source IP, but if it could work, that would be nice and easy.

**Comment by deitch** [comment] 2021-06-29 11:10
No, I don't see it. It just doesn't appear to be within the scope of things that kube-proxy ever does, such that we could (ab)use it. kube-proxy does do SNAT at various rules, but I struggle to see what kind of `Service` would cause it to do the right thing in keeping addresses the same but changing the source address.

**Comment by flokli** [comment] 2021-07-20 10:23
@deitch 
> The issues:
> 
>     * ccm assumes that all nodes are running in EQXM; in reality, it could be multi-cloud.

It might make sense to have the cluster control plane running in one metro, but I can definitely see usecases of highly specific worker nodes that are not running in EQXM, and I'm a bit scared about what the CCM would do with them if it can't find them via the API.

>     * ccm assumes that all nodes are running in one facility; in reality, it could be across multiple facilities in a single metro, or across metros.

Again, assume certain nodes are only available in a specific facility, but you need to extend to another metro due to capacity issues.

>     * ccm assumes that the (single) facility is the only place that the ccm itself is running, and thus it can use metadata to retrieve that facility

With EQXM API credentials, the CCM should be able to query the API from anywhere. The problem really is that the CCM also queries the metadata server. Which facts (except the bgp endpoint addresses?) are only exposed through the metadata server?

As for the "which metro/facility should we allocate Elastic IPs from" question: we could just use an environment variable for this, as of now.

**Comment by deitch** [comment] 2021-07-21 08:14
> Which facts (except the bgp endpoint addresses?) are only exposed through the metadata server?

None. To the best of my knowledge, you can get _everything_ that is available in metadata (and a whole lot more) from the EQXM API. The only exception might be userdata, but even that should be API available, and in any case, ccm never should be getting that.

The metadata is going to have to be removed from it in these scenarios.

**Comment by flokli** [comment] 2021-07-21 12:09
yeah, so I guess we shouldn't use metadata, and then see if this magically fixes some of the problematic assumptions we have right now?

**Comment by deitch** [comment] 2021-07-21 12:16
I don't think it will fix too many things. We still have to sort out the issue of multiple facilities and metros, as well as nodes in non-EQXM facilities (which is not recommended, having clusters with geographically distant nodes, but it is a possibility), which really comes down to the EIP and where it gets created. I don't think the (incorrect) metadata is used elsewhere. Just to get the facility and use that to create loadbalancer EIPs.

We are starting a larger push to resolve a whole bunch of CPEM issues, including this.

**Comment by flokli** [comment] 2021-07-22 23:24
> I don't think it will fix too many things. We still have to sort out the issue of multiple facilities and metros, as well as nodes in non-EQXM facilities (which is not recommended, having clusters with geographically distant nodes, but it is a possibility), which really comes down to the EIP and where it gets created. I don't think the (incorrect) metadata is used elsewhere. Just to get the facility and use that to create loadbalancer EIPs.

There's Global Anycast IPs now, right? I guess one solution could be to fall back to creating those in case there's EQXM nodes in different metros detected - while being able to override this to a "fallback region" via environment variable/config option.
I also think that should probably be configurable per-service via annotations.

> We are starting a larger push to resolve a whole bunch of CPEM issues, including this.

Thanks, looking forward for it!

**Comment by deitch** [comment] 2021-08-16 22:26
> There's Global Anycast IPs now, right? I guess one solution could be to fall back to creating those in case there's EQXM nodes in different metros detected - while being able to override this to a "fallback region" via environment variable/config option.
I also think that should probably be configurable per-service via annotations

Good point, those are a real option.

I don't want us to be detecting anything here, as we are almost guaranteed to get it wrong more often than right. What happens if someone adds a node in a remote data centre after a local EIP is created? Or the other way around?

I think this is the kind of thing that should have a local default and a config to override.

**Comment by deitch** [comment] 2021-08-16 22:33
As interesting as this discussion has been, I would like to start moving it towards something actionable. @displague as you opened it and have insight, we would appreciate more.

I think we are on the same page about:

* metadata is used solely on the CCM node, solely to get the facility, when no facility is provided explicitly via env var/cli/etc
* the retrieved or configured facility is used only to determine where to create an EIP (local public address) for services of `type=LoadBalancer`
* we should get out of using metadata
* we need some other way to determine where to create that EIP
* we want EIP creation for services of `type=LoadBalancer` to be automatic, otherwise service creation loses its dynamic-ness

Assuming we agree on the above, we need the replacement. Some options:

* no metadata, no discovery, you _must_ set the cli/env var for it to work (sort of like how we enable load balancers via `METAL_LB` env var), or you just don't get an EIP or load balancer. The provided config could be a facility (local) or metro (local) or just some keyword like `global` to get a global one
* no metadata, yes discovery; it uses the EQXM API to discover the metro of a specific node and gets an EIP for that metro, unless you explicitly override it using cli/env var (this is the same as previous option, except there is default discovery). The question is, how do you discover the metro? Which node are you going to check, without recreating the current metadata error? You cannot scan all nodes each time, as that is inefficient. Then again, we do add annotations to each node upon creation, so the k8s object contains all of them, so we can do some sort of weighted algorithm but what happens when a new node joins the cluster from somewhere else?
* some other solution?

**Comment by flokli** [comment] 2021-08-19 21:56
Agreed on all of the theses above.

From the proposals, I'd personally prefer the "no metadata, no discovery" part.

 - It makes it super clear where/what kind of EIP is created, as the user explicitly configures it.
   - no need to decide about metro/facility, no dependency on the node running the CCM to be in a specific (or any) EQXM facility, no fuzzy weighted algorithm to decide where to create it, no sudden surprises
 - It could still be made more flexible by allowing some `metal.equinix.com/eip-{type,facility,metro}` annotations on `type=LoadBalancer` services

**Comment by deitch** [comment] 2021-08-20 08:04
Oh, I like your annotation proposal. So it looks like this. When you create a Service of `type=LoadBalancer`:

1. if you have an annotation on the Service, will create an EIP for that Service in the annotation's metro/facility/global; if no annotation...
2. if you have set the cli (fallback to env var) specifying a metro/facility/global, will create an EIP for the Service in the cli/env var's metro/facility/global; if not...
3. will not create an EIP

This is looks like a clear path to me. I really would like @displague and @detiber to weigh in on it; they are sure to see if we missed anything, or if there is something standard coming down the pike that we should use instead / in addition, especially around the annotations.

The other consideration is BYOIP (bring your own IP). We have had some questions about that. We would need a way to flag to CCM, "do not set up any EIP for this Service"; it is easy for all services (no annotations of cli/env var), but what if you want for most, just not for this one?

The way CCM works, it looks for `Service.Spec.LoadBalancerIP`, which load balancer implementations (metallb, kube-vip) consume. If the IP is set already, it just keeps going without dealing with EIP. I _think_ that if, when creating the Service, you set the `LoadBalancerIP`, it should just work. So I think that is covered, but worth testing.

**Comment by deitch** [comment] 2021-08-20 09:07
Confirmed. If you preset the `Service.Spec.LoadBalancerIP`, it just takes it as is (does the correct thing). We should document that, but the BYOIP case is correctly handled.

All that remains is to confirm the proposed behaviour and check if it works with / conflicts / etc plans coming from the SIGs. @displague and @detiber should be able to help there.

**Comment by detiber** [comment] 2021-08-20 13:42
I'm not sure if we are currently setting the "standard topology" labels, but we could potentially leverage those to provide a fallback in the event that an annotation and/or cli flag/env variable are not set: https://github.com/kubernetes/enhancements/blob/0e4d5df19d396511fe41ed0860b0ab9b96f46a2d/keps/sig-architecture/1659-standard-topology-labels/README.md

Granted we would have to formalize agreement that facility ~= zone and metro ~= region for this purpose, but it would also give us the benefit of leveraging topology aware hints for internal service traffic as well: https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/2433-topology-aware-hints

**Comment by deitch** [comment] 2021-08-22 05:59
@detiber I think you are suggesting the following. When someone creates a `Service`, the following is the CCM's logic:

1. If `Service.Spec.LoadBalancerIP` is set, we use it, nothing more to do; if not...
2. If `Service.Metadata.Annotations["topology.kubernetes.io/zone"]` is set, get an EIP for the given facility; if not...
3. If `Service.Metadata.Annotations["topology.kubernetes.io/region"]` is set, get an EIP for the given metro; if not...
4. If the env var or cli flag is set on CCM, get an EIP for the given facility or metro or global; if not...
5. Get no EIP

If this is what you are suggested, I really like it, as it allows us to hew to the topology standard. 

> nted we would have to formalize agreement that facility ~= zone and metro ~= region for this purpose

We are pretty comfortable with that, I believe.

My only concerns are:

* How would someone indicate that they want a global EIP? I guess they could use `region: global`? Would that affect anything else negatively?
* As there are separate annotations for `zone` and `region`, we are deciding arbitrarily that zone overrides region (see my order list above). I am fine with that (this is for a `Service`, not a node or pod), but we need to be explicit about it. Are there any possible negative side-effects to it?

Thanks for the solid direction @detiber

**Comment by detiber** [comment] 2021-08-23 13:59
> @detiber I think you are suggesting the following. When someone creates a `Service`, the following is the CCM's logic:
> 
> 1. If `Service.Spec.LoadBalancerIP` is set, we use it, nothing more to do; if not...
> 2. If `Service.Metadata.Annotations["topology.kubernetes.io/zone"]` is set, get an EIP for the given facility; if not...
> 3. If `Service.Metadata.Annotations["topology.kubernetes.io/region"]` is set, get an EIP for the given metro; if not...
> 4. If the env var or cli flag is set on CCM, get an EIP for the given facility or metro or global; if not...
> 5. Get no EIP
> 
> If this is what you are suggested, I really like it, as it allows us to hew to the topology standard.

I think we should stick with labels over annotations to align more closely with the way topology is already handled in upstream components.

I would probably consider the following priorities instead:

1. If `Service.Spec.LoadBalancerIP` is set, we use it, nothing more to do; if not...
2. If the env var or cli flag is set on CCM, get an EIP for the given facility or metro or global; if not...
3. If `Service.Metadata.Labels["topology.kubernetes.io/region"]` is set, get an EIP for the given metro; if not...
4. If `Service.Metadata.Labels["topology.kubernetes.io/zone"]` is set, get an EIP for the given facility; if not...
5. Get no EIP

Mainly, because I think if the user is specifying it at the CCM layer, then they are explicitly setting what they want for the entire cluster. Though, it may not hurt to have 2 configuration options at the CCM layer, one to set configuration for all services, and one to set the "default" if not specified on the Service.

I also think we should likely prefer to do metro based IPs over facility based IPs, unless there is a specific reason not to. As far as I'm aware, we are moving towards metro-based defaults in general. Unless there is a specific use case where facility based EIPs are preferable over metro-based EIPs, I think we should likely always prefer metro EIPs over facility.

> * How would someone indicate that they want a global EIP? I guess they could use `region: global`? Would that affect anything else negatively?

I think I actually prefer making the user jump through hoops in order to get a global EIP, mainly because multi-metro clusters should be an anti-pattern. Any users that are running a multi-metro cluster should only be doing so if they fully understand the potential issues related to it.

With that in mind, I think there should be a specific opt-in flag for the CCM that needs to be enabled to even allow global EIP allocation. We could also introduce our own annotation to specify a global EIP, that way we don't need to override the region topology label in a weird way.

> * As there are separate annotations for `zone` and `region`, we are deciding arbitrarily that zone overrides region (see my order list above). I am fine with that (this is for a `Service`, not a node or pod), but we need to be explicit about it. Are there any possible negative side-effects to it?

I think I prefer the other way, if both zone and region are specified, then I think we should default to region/metro over zone/facility.

While I don't think we should target this for the initial implementation, we could eventually introspect the system and create the EIP automatically with the best "fit" based on the workload targeted by the Service.
Super Naive implementation:
- Check Nodes in system.
  - If all in same zone: use zone (?? do we even really need this, is there a use case where this is beneficial?)
  - If all in same metro: use metro
  - Else: use global
Less Naive implementation:
- Check pods that match service label selector:
  - Narrow down nodes based on taints/tolerations/nodeselector:
    - If all in same zone: use zone (?? do we even really need this, is there a use case where this is beneficial?)
    - If all in same metro: use metro
    - Else: use global
Least Naive implementation:
- Check all resources that contain a Pod spec that would match the service label selector:
  - Narrow down nodes based on taints/tolerations/nodeselector:
    - If all in same zone: use zone (?? do we even really need this, is there a use case where this is beneficial?)
    - If all in same metro: use metro
    - Else: use global

Granted these do not take into account a cluster growing outside of it's current architecture, so that would take further planning to prevent issues cropping up down the line.

As an aside, if we aren't already assigning the topology based labels to Nodes in the CCM, we should likely start.

**Comment by detiber** [comment] 2021-08-23 14:07
Answering my own question...  It looks like we are currently setting the zone label, but will need to update to supporting InstancesV2, in order to be able to support setting Region.

**Comment by displague** [comment] 2021-08-23 15:23
> If Service.Metadata.Annotations["topology.kubernetes.io/zone"] is set, get an EIP for the given facility; if not...

With some exceptions, most 'facility' EIPs are now metro portable.  The exceptions tend to be in facilities that most users 
 (especially new users) do not have access to.

**Comment by deitch** [comment] 2021-08-23 16:09
> As an aside, if we aren't already assigning the topology based labels to Nodes in the CCM, we should likely start.


As you wrote, we are not. We should start. Please open an issue, so we can track it?

**Comment by deitch** [comment] 2021-08-23 16:10
> With some exceptions, most 'facility' EIPs are now metro portable. The exceptions tend to be in facilities that most users
(especially new users) do not have access to.

Really. I didn't know that. Does that mean that, for all intents and purposes, there is no difference between an EIP being targeted at a facility and an EIP targeted at a metro? So we can simplify the above logic?

**Closed** 2022-01-24 14:01 UTC
